### ISSUE TITLE
Enable Squashing

### ISSUE THREAD

**Issue by iJustLeyxo** [jon011235/MARVIN#10]
Apparently squashing (squash-merging) is currently not enabled. I suggest it be enabled for quality-of-life improvements.

**Comment by jon011235** [comment]
Why do you suppose it is disabled? looking at the settings I only found a checkbox for squashing pull requests (the option is enabled)
And doing a quick online search I found no option I could enable

**Comment by iJustLeyxo** [comment]
When I tried to squash a gitignore pull request, there was an error and the merge was executed normally without squashing. I suppose these are the settings you were talking about:

![Screenshot_2023-10-25_21-47-12](https://github.com/jon011235/MARVIN/assets/92861073/c4aa3b2e-ee79-4451-b548-820408b5fb5c)

**Comment by iJustLeyxo** [comment]
It is also possible that certain merge types have been disabled for specific collaborators or collaborators in general in the menu for collaborators in the repo settings.

**Comment by jon011235** [comment]
![grafik](https://github.com/jon011235/MARVIN/assets/148149771/f56f8ee1-3b88-4238-b526-30910b74d0e2)
![grafik](https://github.com/jon011235/MARVIN/assets/148149771/e5ae2af0-6677-437e-9892-040ac9c86da4)

In neither settings regions i found a suiting option the first image is identical to the image you provided and is also the option i refered to earlier

**Comment by iJustLeyxo** [comment]
Squashing now works. It may have just been a temporary issue with GitHub.
