### ISSUE TITLE
Which coding style should we use?

### ISSUE THREAD

**Issue by jon011235** [jon011235/MARVIN#8]
I guess for the sake of consistency it would be nice to have one coding style.
Here are a few things i noticed which we might want to standardize:

## Suggestions

- Name of the reset signal. Mattis is using 'rst'. Furthermore we should only use high-active resets
- folder structur: As already agreed on we will have a 'src' and i would furthermore suggest a 'utility' folder containing the modelsim and quartus files shared by all of us
- I guess we will use the normal convention that constants are capital and variables are small and follow the snake case convention
- Documentation of the file in its beginning like this:
```
//////////////////////////////////////////////////////////////////////
// Project : MARVIN/VGA
// Module  : toplevel_debug
// Description: pass debug data to the FPGA
//
// Authors : Mattis Levin Hänsel
//
//////////////////////////////////////////////////////////////////////
```

## Documentation
Some of those issues where already discussed in [this pr](https://github.com/jon011235/MARVIN/pull/7/)
Furthermore I will document the coding style in the wiki

**Comment by jon011235** [comment]
Proposed coding style: https://github.com/jon011235/MARVIN/wiki/Coding-Style

**Comment by iJustLeyxo** [comment]
I accidentally merged the old "Standards" file and your new "Coding Style" into [Style Guidelines](https://github.com/jon011235/MARVIN/wiki/Style-Guidelines) before seeing this issue. However, I refined the idea and added a bunch of additional points (please [have a look at them in the wiki](https://github.com/jon011235/MARVIN/wiki/Style-Guidelines)). The main difference is your header, where I suggest that:
- We use block comment format so multi-line descriptions, etc. are easier to add.
- No right border of the comment box (also for multi-line descriptions)
- The lower border doesn't use "/" symbols and instead something like "-", "_" or "=" for better readability
With the goal of the header being less cluttered and easier to edit.

**Comment by jon011235** [comment]
@DM8AT @MineMuse @Luftsirene 
Are those guidelines alright for you?
